### ISSUE TITLE
BomJsonGenerator.toJsonString() unexpectedly replaces all new lines in Strings with spaces

### ISSUE THREAD

**Issue by benken-parasoft** [CycloneDX/cyclonedx-core-java#394] opened 2024-04-12 20:40 UTC
If I serialize a org.cyclonedx.model.Bom to JSON using BomJsonGenerator.toJsonString() then I unexpectedly lose newlines in various strings, like license and copyright text where new lines are especially important.

I tracked down the problem to org.cyclonedx.util.serializer.TrimStringSerializer.  This serializer is not just trimming but is also replacing carriage return, line feed, and tab characters with a space.  These should be preserved in the JSON.  Jackson will correctly escape such characters, like encoding newlines as '\n'.

In contrast, BomXmlGenerator is fine.  The XML version has newlines correctly preserved in the XML.

I am currently working around the issue as follows:
```
    private static void removeTrimStringSerializer(BomJsonGenerator jsonGenerator) {
        ObjectMapper mapper = ((AbstractBomJsonGenerator) jsonGenerator).getMapper();
        SerializerFactory newSerializerFactory = BeanSerializerFactory.instance;
        SerializationConfig serializationConfig = mapper.getSerializationConfig();
        JavaType javaType = serializationConfig.constructType(String.class);
        BeanDescription beanDesc = serializationConfig.introspect(javaType);
        SerializerFactoryConfig serializerFactoryConfig = ((BasicSerializerFactory) mapper.getSerializerFactory()).getFactoryConfig();
        for (Serializers serializers : serializerFactoryConfig.serializers()) {
            JsonSerializer<?> stringSerializer = serializers.findSerializer(serializationConfig, javaType, beanDesc);
            if (!(stringSerializer instanceof TrimStringSerializer)) {
                newSerializerFactory = newSerializerFactory.withAdditionalSerializers(serializers);
            }
        }
        mapper.setSerializerFactory(newSerializerFactory);
    }
```

**Comment by nscuro** [comment] 2024-06-18 17:29
Appears to be a duplicate of #394.

**Closed by nscuro** 2024-06-18 17:29 UTC
Labels: duplicate

**Comment by benken-parasoft** [comment] 2024-06-18 17:32
> Appears to be a duplicate of https://github.com/CycloneDX/cyclonedx-core-java/issues/394

A duplicate of itself?
This is a real issue.  Copyright and license text can be large with a lot of newlines.  BomJsonGenerator strips them out!

**Comment by nscuro** [comment] 2024-06-18 17:34
Too much copy-pasting. Meant to link to #135.

**Comment by benken-parasoft** [comment] 2024-06-18 18:07
> Too much copy-pasting. Meant to link to https://github.com/CycloneDX/cyclonedx-core-java/issues/135.

Thanks!  I'll follow this one instead.
